apiVersion: v1
kind: Service
metadata:
  name: kub-service
  labels:
    app: kub
spec:
  selector:
    app: kub
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30552